### PR TITLE
added support for nested groups

### PR DESCRIPTION
**Pull request by awolden**
This adds support the nesting of groups within crowd. It also seems like my editor cleaned up some trailing white-space.

### CODE REVIEW

**Comment by awolden** [comment]
@dsn I am not sure if you are maintaining this repository anymore, but we are looking at using it in a couple enterprise applications we are building out. What is your current roadmap for this repo?

**Comment by dsn** [comment]
@awolden I wrote this years ago for a few projects used by a previous employer and have since changed jobs and as a result I have lost access to a Crowd server. It had been so long since I have touched this I kind of forgot it was still out there so I don't really have any current plans with it. The best I can say at the moment is that I am more than happy to accept pull requests and will try my best to get to them in a timely manner. If I get some free time I will try to get a Crowd VM running at home and get around to finishing some of the missing features and documentation but I cannot make any promises.

**Comment by awolden** [comment]
@dsn That'll be fine, I am more than happy to make a PR if I need something. What about publishing new versions to NPM?

**Comment by dsn** [comment]
sorry for the delay in responding, I was finally able to get back into my
NPM account and have pushed the latest version in git up to NPM.

On Fri, Jun 26, 2015 at 12:13 AM, Alexander Wolden <notifications@github.com

**Pull request merged**
